CREATE TABLE n8n_db.public.message (
  id text NOT NULL,
  created_date_time timestamp NULL,
  last_modified_date_time timestamp NULL,
  categories _text NULL,
  received_date_time timestamp NULL,
  sent_date_time timestamp NULL,
  has_attachments bool NULL,
  internet_message_id text NULL,
  subject text NULL,
  body_preview text NULL,
  importance text NULL,
  conversation_id text NULL,
  is_read bool NULL,
  web_link text NULL,
  inference_classification text NULL,
  body_content_type text NULL,
  body_content text NULL,
  sender_name text NULL,
  sender_email text NULL,
  from_name text NULL,
  from_email text NULL,
  to_recipients _jsonb NULL,
  cc_recipients _jsonb NULL,
  bcc_recipients _jsonb NULL,
  reply_to _jsonb NULL,
  summary text NULL,
  tags _text NULL,
  draft text NULL,
  CONSTRAINT message_pkey PRIMARY KEY (id)
);
